<?php

return [
    'root' => env('FOLDER_VIDEO_ROOT', 'Z:\video(重跑)'),
    'good_subdirectory' => env('FOLDER_VIDEO_GOOD_SUBDIRECTORY', 'good'),
    'ffmpeg_bin' => env('FOLDER_VIDEO_FFMPEG_BIN', 'C:\ffmpeg\bin\ffmpeg.exe'),
    'ffprobe_bin' => env('FOLDER_VIDEO_FFPROBE_BIN', 'C:\ffmpeg\bin\ffprobe.exe'),
    'preview_cache_path' => env('FOLDER_VIDEO_PREVIEW_CACHE_PATH', storage_path('app/folder-video-previews')),
    'preview_queue_path' => env('FOLDER_VIDEO_PREVIEW_QUEUE_PATH', storage_path('app/folder-video-preview-queue')),
    'tv_preview_cache_path' => env('FOLDER_VIDEO_TV_PREVIEW_CACHE_PATH', storage_path('app/folder-video-previews/tv-animated')),
    'tv_hls_cache_path' => env('FOLDER_VIDEO_TV_HLS_CACHE_PATH', storage_path('app/folder-video-tv-hls')),
    'tv_hls_queue_path' => env('FOLDER_VIDEO_TV_HLS_QUEUE_PATH', storage_path('app/folder-video-tv-hls-queue')),
    'tv_hls_segment_seconds' => (int) env('FOLDER_VIDEO_TV_HLS_SEGMENT_SECONDS', 2),
    'thumbnail_cache_path' => env('FOLDER_VIDEO_THUMBNAIL_CACHE_PATH', storage_path('app/folder-video-thumbnails')),
    'stream_base_path' => env('FOLDER_VIDEO_STREAM_BASE_PATH', ''),
    'preview_seconds' => (int) env('FOLDER_VIDEO_PREVIEW_SECONDS', 18),
    'preview_height' => (int) env('FOLDER_VIDEO_PREVIEW_HEIGHT', 360),
    'preview_timeout' => (int) env('FOLDER_VIDEO_PREVIEW_TIMEOUT', 90),
    'preview_fallback_to_source' => env('FOLDER_VIDEO_PREVIEW_FALLBACK_TO_SOURCE', true),
    'thumbnail_second' => (int) env('FOLDER_VIDEO_THUMBNAIL_SECOND', 2),
    'thumbnail_width' => (int) env('FOLDER_VIDEO_THUMBNAIL_WIDTH', 480),
    'thumbnail_timeout' => (int) env('FOLDER_VIDEO_THUMBNAIL_TIMEOUT', 45),
    'index_filename' => env('FOLDER_VIDEO_INDEX_FILENAME', 'folder-video-index.json'),
    'index_path' => env('FOLDER_VIDEO_INDEX_PATH'),
    'extensions' => ['mp4', 'm4v', 'mov', 'mkv', 'webm', 'avi'],
    'probe_on_request' => env('FOLDER_VIDEO_PROBE_ON_REQUEST', false),
    'index_refresh_seconds' => (int) env('FOLDER_VIDEO_INDEX_REFRESH_SECONDS', 300),
    'app_version' => env('FOLDER_VIDEO_APP_VERSION', '2026.07.11.25'),
    'app_preview_max_connections' => (int) env('FOLDER_VIDEO_APP_PREVIEW_MAX_CONNECTIONS', 36),
    'app_page_limit' => (int) env('FOLDER_VIDEO_APP_PAGE_LIMIT', 36),
    'android_apk_version_code' => (int) env('FOLDER_VIDEO_ANDROID_APK_VERSION_CODE', 14),
    'android_apk_version_name' => env('FOLDER_VIDEO_ANDROID_APK_VERSION_NAME', '2026.07.11.14'),
    'android_apk_path' => env('FOLDER_VIDEO_ANDROID_APK_PATH', storage_path('app/folder-video-app.apk')),
    'tv_android_apk_version_code' => (int) env('FOLDER_VIDEO_TV_ANDROID_APK_VERSION_CODE', 11),
    'tv_android_apk_version_name' => env('FOLDER_VIDEO_TV_ANDROID_APK_VERSION_NAME', '2026.07.11.11-tv'),
    'tv_android_apk_path' => env('FOLDER_VIDEO_TV_ANDROID_APK_PATH', storage_path('app/folder-video-tv.apk')),
];
