<?php

return [
    // Fixed qualitative assessments as of 2026-10-01; shared by all snapshots.
    // Higher means easier substitution by peers / transfer of orders, not a probability.
    // Official sources support product/technology facts; the levels are editorial judgments.
    // Do not derive from valuation groups or update in weekly EPS/AI jobs.
    // New/unreviewed stocks stay 待評估. Source dates may predate the assessment.
    'stocks' => [
        '3481' => [
            'stock_name' => '群創',
            'level' => '高',
            'basis' => '主力顯示面板規格可比較，客戶較易配置替代供應商；特殊顯示仍有差異化',
            'source_url' => 'https://www.innolux.com/Uploads/22/2023Annual%20Report_5397ad.pdf',
            'assessed_at' => '2026-10-01',
        ],
        '2408' => [
            'stock_name' => '南亞科',
            'level' => '高',
            'basis' => '標準DRAM介面與規格通用性高，品質有門檻但可驗證其他供應商',
            'source_url' => 'https://www.nanya.com/en/Product/',
            'assessed_at' => '2026-10-01',
        ],
        '2344' => [
            'stock_name' => '華邦電',
            'level' => '中',
            'basis' => '利基記憶體與長供貨週期增加黏著度，標準介面仍有替代空間',
            'source_url' => 'https://www.winbond.com/hq/application/wplp/?__locale=en_TW',
            'assessed_at' => '2026-10-01',
        ],
        '8299' => [
            'stock_name' => '群聯',
            'level' => '低',
            'basis' => '控制器、韌體與NAND整合客製設計提高轉換及重新驗證成本',
            'source_url' => 'https://www.phison.com/imagin-plus-platform-customized-nand-flash-storage-solutions-and-asic-design-services/',
            'assessed_at' => '2026-10-01',
        ],
        '1303' => [
            'stock_name' => '南亞',
            'level' => '高',
            'basis' => '塑膠纖維與大宗化學材料同規格替代性高，高階電子材料驗證降低部分風險',
            'source_url' => 'https://www.npc.com.tw/j2npc/zhtw/appcate/all',
            'assessed_at' => '2026-10-01',
        ],
        '8046' => [
            'stock_name' => '南電',
            'level' => '低',
            'basis' => '高階ABF細線路、多層堆疊與封裝驗證形成轉換門檻',
            'source_url' => 'https://www.nanyapcb.com.tw/nypcb/chinese/Technology/ABFSRoadmap',
            'assessed_at' => '2026-10-01',
        ],
        '3037' => [
            'stock_name' => '欣興',
            'level' => '低',
            'basis' => 'IC載板及高密度互連需匹配晶片封裝設計，可靠度驗證增加轉單成本',
            'source_url' => 'https://www.uniflex.com.tw/esg/en/product01.html',
            'assessed_at' => '2026-10-01',
        ],
        '3376' => [
            'stock_name' => '新日興',
            'level' => '中',
            'basis' => '客製樞紐精密製造與專利有門檻，新機種仍可重新選擇合格供應商',
            'source_url' => 'https://www.szs-group.com/page/about-company',
            'assessed_at' => '2026-10-01',
        ],
        '3189' => [
            'stock_name' => '景碩',
            'level' => '低',
            'basis' => 'FC-BGA、SiP載板精密製程及封裝可靠度驗證提高轉換成本',
            'source_url' => 'https://www.kinsus.com.tw/en',
            'assessed_at' => '2026-10-01',
        ],
        '6505' => [
            'stock_name' => '台塑化',
            'level' => '高',
            'basis' => '油品石化基本原料較標準化，客戶可比價換源；集團物流提供部分黏著度',
            'source_url' => 'https://www.fpcc.com.tw/uploads/images/ir/%E5%8F%B0%E5%A1%91%E7%9F%B3%E5%8C%96113%E5%B9%B4%E8%82%A1%E6%9D%B1%E6%9C%83%E5%B9%B4%E5%A0%B1.pdf',
            'assessed_at' => '2026-10-01',
        ],
        '4971' => [
            'stock_name' => 'IET-KY',
            'level' => '低',
            'basis' => 'MBE磊晶與客製材料結構具門檻，替換需驗證元件性能及製程匹配',
            'source_url' => 'https://intelliepi.com/products/',
            'assessed_at' => '2026-10-01',
        ],
        '6213' => [
            'stock_name' => '聯茂',
            'level' => '低',
            'basis' => '高頻高速及車用板材配方、電性與可靠度驗證提高導入後轉單成本',
            'source_url' => 'https://www.iteqcorp.com/',
            'assessed_at' => '2026-10-01',
        ],
        '6274' => [
            'stock_name' => '台燿',
            'level' => '低',
            'basis' => '低損耗材料匹配訊號完整性及板廠製程，認證可靠度要求提高轉換成本',
            'source_url' => 'https://www.tuc.com.tw/en-us/products2',
            'assessed_at' => '2026-10-01',
        ],
        '2383' => [
            'stock_name' => '台光電',
            'level' => '低',
            'basis' => '高階低損耗材料與專利配方有差異化，替換需重新驗證電性製程',
            'source_url' => 'https://www.emctw.com/zh-TW/about_milestone/index',
            'assessed_at' => '2026-10-01',
        ],
        '3491' => [
            'stock_name' => '昇達科',
            'level' => '低',
            'basis' => '微波毫米波元件客製設計，精密製造及低損耗性能提高替換成本',
            'source_url' => 'https://www.umt-tw.com/tw/index.php',
            'assessed_at' => '2026-10-01',
        ],
        '6515' => [
            'stock_name' => '穎崴',
            'level' => '低',
            'basis' => '測試介面溫控方案客製匹配晶片及測試條件，重新導入需驗證',
            'source_url' => 'https://www.winwayglobal.com/zh-TW',
            'assessed_at' => '2026-10-01',
        ],
        '6223' => [
            'stock_name' => '旺矽',
            'level' => '低',
            'basis' => '探針卡整合客製載板探針與訊號完整性，重新設計驗證有門檻',
            'source_url' => 'https://www.mpi.com.tw/probecard/',
            'assessed_at' => '2026-10-01',
        ],
        '3653' => [
            'stock_name' => '健策',
            'level' => '低',
            'basis' => '依晶片架構與功耗共同設計散熱，精密加工與垂直整合提高替換門檻',
            'source_url' => 'https://www.jentech.com.tw/zh',
            'assessed_at' => '2026-10-01',
        ],
        '2409' => [
            'stock_name' => '友達',
            'level' => '高',
            'basis' => '傳統面板競爭及替代性高，車用商用客製顯示降低部分風險',
            'source_url' => 'https://www.auo.com/upload/media/ir/2025_AUO_Annual_Report_EN.pdf',
            'assessed_at' => '2026-10-01',
        ],
        '6510' => [
            'stock_name' => '精測',
            'level' => '低',
            'basis' => '探針卡客製訊號完整性、熱與機構設計，替換須重新驗證測試效能',
            'source_url' => 'https://www.chpt.com/xmdoc/cont?sid=0L158502416391397096&xsmsid=0G328551704882485281',
            'assessed_at' => '2026-10-01',
        ],
        '3167' => [
            'stock_name' => '大量',
            'level' => '中',
            'basis' => '精密設備、自研控制器與售後服務有門檻，新設備採購仍可比較其他供應商',
            'source_url' => 'https://www.taliang.com/',
            'assessed_at' => '2026-10-01',
        ],
        '3443' => [
            'stock_name' => '創意',
            'level' => '低',
            'basis' => '客製ASIC整合IP、實體設計與先進封裝，專案轉移需重新設計驗證',
            'source_url' => 'https://www.guc-asic.com/upload/2026_04_16/8_202604161551145dnuwxrHk5.pdf',
            'assessed_at' => '2026-10-01',
        ],
        '2368' => [
            'stock_name' => '金像電',
            'level' => '低',
            'basis' => '高階伺服器板要求高層數、低損耗與訊號完整性，製程可靠度門檻高',
            'source_url' => 'https://www.gce.com.tw/product.html',
            'assessed_at' => '2026-10-01',
        ],
        '4958' => [
            'stock_name' => '臻鼎-KY',
            'level' => '中',
            'basis' => '高階HDI製程可靠度有門檻，但多種PCB產品整體仍有同業替代空間',
            'source_url' => 'https://www.zdtco.com/tw/product/%E9%AB%98%E5%AF%86%E5%BA%A6%E9%80%A3%E6%8E%A5%E6%9D%BF',
            'assessed_at' => '2026-10-01',
        ],
        '2059' => [
            'stock_name' => '川湖',
            'level' => '低',
            'basis' => '伺服器滑軌專利與OEM/ODM認證、機構配合提高更換成本',
            'source_url' => 'https://www.kingslide.com/about_research',
            'assessed_at' => '2026-10-01',
        ],
        '5274' => [
            'stock_name' => '信驊',
            'level' => '極低',
            'basis' => 'BMC硬體韌體深度整合，伺服器可靠度及既有平台導入形成很高轉換門檻',
            'source_url' => 'https://www.aspeedtech.com/investor_faq/',
            'assessed_at' => '2026-10-01',
        ],
        '9921' => [
            'stock_name' => '巨大',
            'level' => '高',
            'basis' => '品牌製造有差異化，但自行車購買少有系統綁定，易比較替代品牌',
            'source_url' => 'https://origin.giantgroup-cycling.com/files/images/iroverview/Annual%20report/Eng/114_Annual_Report_EN.pdf',
            'assessed_at' => '2026-10-01',
        ],
        '3017' => [
            'stock_name' => '奇鋐',
            'level' => '中',
            'basis' => '整機散熱有工程門檻，產品涵蓋風扇散熱件機箱，可替代性依產品而異',
            'source_url' => 'https://www.avc.co/en-us/',
            'assessed_at' => '2026-10-01',
        ],
        '2454' => [
            'stock_name' => '聯發科',
            'level' => '中',
            'basis' => 'SoC軟硬體平台有設計門檻，終端週期短，新機種可改採競爭平台',
            'source_url' => 'https://www.mediatek.com/hubfs/728015/MediaTek%20Assets/Pdfs/Annual%20Reports/2024-English-Annual-Report.pdf',
            'assessed_at' => '2026-10-01',
        ],
        '7711' => [
            'stock_name' => '永擎',
            'level' => '中',
            'basis' => '伺服器客製及ODM/JDM有黏著度，共通晶片平台仍可選其他系統商',
            'source_url' => 'https://www.asrockrack.com/general/Investor/AnnualReport%28115%29.pdf',
            'assessed_at' => '2026-10-01',
        ],
        '3711' => [
            'stock_name' => '日月光投控',
            'level' => '低',
            'basis' => '先進封裝SiP及測試整合牽涉設計可靠度驗證，替換門檻高於一般組裝',
            'source_url' => 'https://ase.aseglobal.com/system-in-package/',
            'assessed_at' => '2026-10-01',
        ],
        '6446' => [
            'stock_name' => '藥華藥',
            'level' => '低',
            'basis' => 'BESREMi核准生物藥替代涉及臨床法規門檻，仍有其他療法；此處指產品療法替代',
            'source_url' => 'https://purplebooksearch.fda.gov/index.cfm?blaNo=761166&event=productdetails',
            'assessed_at' => '2026-10-01',
        ],
        '6805' => [
            'stock_name' => '富世達',
            'level' => '低',
            'basis' => '轉軸非標準客製、前期共同開發精密製程專利提高替換成本',
            'source_url' => 'https://www.fositek.com/Portals/0/FileUpload/Shareholders/2025/2025AnnualReport.pdf',
            'assessed_at' => '2026-10-01',
        ],
        '3036' => [
            'stock_name' => '文曄',
            'level' => '中',
            'basis' => '代理線技術支援與全球供應鏈有黏著度，通路仍有競爭替代空間',
            'source_url' => 'https://www.wtmec.com/wp-content/uploads/2026/04/WT_2025-Annual-Report_CHINESE.pdf',
            'assessed_at' => '2026-10-01',
        ],
        '6488' => [
            'stock_name' => '環球晶',
            'level' => '低',
            'basis' => '矽晶圓純度製程一致性要求高，替代料須驗證，仍有其他大型供應商',
            'source_url' => 'https://www.sas-globalwafers.com/en/finance/2025-2/globalwafers_2024-annual-report-en/',
            'assessed_at' => '2026-10-01',
        ],
        '2308' => [
            'stock_name' => '台達電',
            'level' => '低',
            'basis' => '電源散熱系統整合有設計導入門檻，整體方案較難直接替換',
            'source_url' => 'https://www.deltaww.com/en-US/company/our-businesses/power-electronics',
            'assessed_at' => '2026-10-01',
        ],
        '3661' => [
            'stock_name' => '世芯-KY',
            'level' => '低',
            'basis' => '先進ASIC與IP封裝高度客製，既有專案轉換成本高，新案仍可另選夥伴',
            'source_url' => 'https://www.alchip.com/en',
            'assessed_at' => '2026-10-01',
        ],
        '6415' => [
            'stock_name' => '矽力-KY',
            'level' => '中',
            'basis' => '類比電源IC有導入可靠度門檻，通用產品替代選項較多',
            'source_url' => 'https://www.silergy.com/quality',
            'assessed_at' => '2026-10-01',
        ],
        '3035' => [
            'stock_name' => '智原',
            'level' => '低',
            'basis' => '自有IP與客製ASIC流程整合，既有設計切換成本高，新案仍可競標',
            'source_url' => 'https://www.faraday-tech.com/en/entry/AboutFaraday',
            'assessed_at' => '2026-10-01',
        ],
        '2313' => [
            'stock_name' => '華通',
            'level' => '中',
            'basis' => 'HDI微孔高密度線路有製程門檻，合格同業仍可承接',
            'source_url' => 'https://www.compeq.com.tw/product_view.php?gid=f7b2917a-9a04-11ec-89fb-005056a9caf8',
            'assessed_at' => '2026-10-01',
        ],
        '2049' => [
            'stock_name' => '上銀',
            'level' => '中',
            'basis' => '螺桿滑軌精度壽命有差異，標準品選擇多，替換需機構驗證',
            'source_url' => 'https://hiwin.com/products/ballscrews-supports/',
            'assessed_at' => '2026-10-01',
        ],
        '3081' => [
            'stock_name' => '聯亞',
            'level' => '低',
            'basis' => '光通訊磊晶成長與結構控制複雜，客製開發有黏著度，仍有專業廠替代',
            'source_url' => 'https://www.lmoc.com.tw/index.php?i=1&id=390&lang=cht&option=module&task=dfile',
            'assessed_at' => '2026-10-01',
        ],
        '2345' => [
            'stock_name' => '智邦',
            'level' => '中',
            'basis' => '高速交換器共同設計量產驗證有門檻，開放平台仍可選其他ODM',
            'source_url' => 'https://www.accton.com/all-in-one-services/',
            'assessed_at' => '2026-10-01',
        ],
        '3665' => [
            'stock_name' => '貿聯-KY',
            'level' => '中',
            'basis' => '客製線束及系統整合提高切換成本，亦有標準互連件，依應用而異',
            'source_url' => 'https://www.bizlinktech.com/capabilities',
            'assessed_at' => '2026-10-01',
        ],
        '3324' => [
            'stock_name' => '雙鴻',
            'level' => '中',
            'basis' => '液冷與客製散熱提高導入門檻，仍有同業技術替代需重驗效能',
            'source_url' => 'https://www.auras.com.tw/CMSFS/InformationCenters/English/ecfc7b18-d55e-4ca3-a673-b449f83d051c.pdf',
            'assessed_at' => '2026-10-01',
        ],
        '3105' => [
            'stock_name' => '穩懋',
            'level' => '低',
            'basis' => '砷化鎵代工緊密配合客戶電路製程，轉廠須重做驗證及良率爬升',
            'source_url' => 'https://www.winfoundry.com/en-US/About/about_company',
            'assessed_at' => '2026-10-01',
        ],
        '3231' => [
            'stock_name' => '緯創',
            'level' => '中',
            'basis' => 'ODM設計供應鏈量產整合有門檻，仍可選其他夥伴，依產品複雜度而異',
            'source_url' => 'https://www.wistron.com/en/TechnologyLeadership',
            'assessed_at' => '2026-10-01',
        ],
        '3131' => [
            'stock_name' => '弘塑',
            'level' => '低',
            'basis' => '濕製程設備連動客戶製程良率，客製與現場服務提高換機驗證成本',
            'source_url' => 'https://www.gptc.com.tw/about/esg/',
            'assessed_at' => '2026-10-01',
        ],
        '6285' => [
            'stock_name' => '啟碁',
            'level' => '中',
            'basis' => '射頻天線軟硬體整合認證有門檻，仍可由合格同業重新開發',
            'source_url' => 'https://www.wnc.com.tw/en/about/wnc',
            'assessed_at' => '2026-10-01',
        ],
        '4551' => [
            'stock_name' => '智伸科',
            'level' => '低',
            'basis' => '汽車安全醫療精密零件重視加工一致性與品質認證，替換須重新驗證',
            'source_url' => 'https://global.com.tw/%E9%97%9C%E6%96%BC%E6%99%BA%E4%BC%B8/',
            'assessed_at' => '2026-10-01',
        ],
        '2455' => [
            'stock_name' => '全新',
            'level' => '低',
            'basis' => 'MOCVD磊晶與客戶協同研發有材料製程門檻，替換須重驗結構品質',
            'source_url' => 'https://www.vpec.com.tw/vpec/homeweb/about.php?level=2&menu1=M100001&menu2=M200019',
            'assessed_at' => '2026-10-01',
        ],
        '2303' => [
            'stock_name' => '聯電',
            'level' => '中',
            'basis' => '特殊製程設計套件車規驗證形成轉廠門檻，成熟製程仍有其他供應選擇',
            'source_url' => 'https://www.umc.com/en/Product/technologies/Index/specialty',
            'assessed_at' => '2026-10-01',
        ],
        '6239' => [
            'stock_name' => '力成',
            'level' => '中',
            'basis' => '封裝測試程式及良率認證增加切換成本，記憶體封測仍有同業替代',
            'source_url' => 'https://www.pti.com.tw/',
            'assessed_at' => '2026-10-01',
        ],
        '2360' => [
            'stock_name' => '致茂',
            'level' => '低',
            'basis' => '精密量測、專用測試及客製自動化整合提高替換驗證成本',
            'source_url' => 'https://www.chromaate.com/en/test_solutions/photonics_test_solution',
            'assessed_at' => '2026-10-01',
        ],
        '3044' => [
            'stock_name' => '健鼎',
            'level' => '中',
            'basis' => 'PCB製程品質量產驗證有門檻，整體仍面對多家板廠競爭',
            'source_url' => 'https://www.tripod-tech.com/main/2',
            'assessed_at' => '2026-10-01',
        ],
        '2449' => [
            'stock_name' => '京元電子',
            'level' => '低',
            'basis' => '自製高功率燒機設備、客製測試及軟硬整合提高高階測試轉換成本',
            'source_url' => 'https://www.kyec.com.tw/en/Service/technology-innovation',
            'assessed_at' => '2026-10-01',
        ],
        '2330' => [
            'stock_name' => '台積電',
            'level' => '極低',
            'basis' => '先進製程封裝及設計生態系高度整合，轉廠需大幅重新設計驗證',
            'source_url' => 'https://investor.tsmc.com/static/annualReports/2025/english/index.html',
            'assessed_at' => '2026-10-01',
        ],
        '2327' => [
            'stock_name' => '國巨',
            'level' => '中',
            'basis' => '車工規高可靠度特殊元件有認證門檻，標準被動元件仍有替代來源',
            'source_url' => 'https://yageogroup.com/content/Resource%20Library/Financial/Yageo%202025%20Annual%20Report_e.pdf',
            'assessed_at' => '2026-10-01',
        ],
        '2324' => [
            'stock_name' => '仁寶',
            'level' => '中',
            'basis' => '客製研發量產品質全球製造增加轉單成本，成熟ODM仍可由同業承接',
            'source_url' => 'https://www.compal.com/static/file/CompalIntro_2025_EN.pdf',
            'assessed_at' => '2026-10-01',
        ],
        '2376' => [
            'stock_name' => '技嘉',
            'level' => '中',
            'basis' => '伺服器散熱整合驗證有門檻，標準平台板卡仍有同業替代',
            'source_url' => 'https://www.gigabyte.com/Enterprise',
            'assessed_at' => '2026-10-01',
        ],
        '2395' => [
            'stock_name' => '研華',
            'level' => '低',
            'basis' => '工業嵌入式設計、軟體整合及長供貨週期提高換廠重新設計驗證成本',
            'source_url' => 'https://www2.advantech.com/DMS/Services/Longevity-Services.aspx',
            'assessed_at' => '2026-10-01',
        ],
        '2301' => [
            'stock_name' => '光寶科',
            'level' => '中',
            'basis' => '高效電源安規客製伺服器設計有門檻，模組化產品仍有合格同業',
            'source_url' => 'https://www.liteon.com/en/solutions/',
            'assessed_at' => '2026-10-01',
        ],
        '2317' => [
            'stock_name' => '鴻海',
            'level' => '中',
            'basis' => '全球量產軟硬整合供應鏈規模提高移轉難度，訂單仍可分配其他代工廠',
            'source_url' => 'https://www.foxconn.com/en-us/about/group-profile',
            'assessed_at' => '2026-10-01',
        ],
    ],
];
